export const SITE_TITLE = "Harmony Blog";
export const SITE_DESCRIPTION = "Harmony Blogは、最小限の機能で、高速でSEOに優しいAstroのテーマです。本文を含む全てのテキストに対して、「アキ」の調整が行われます。";
export const TITLE_SEPARATOR = " | ";
export const BREADCRUMBS_ARIA_LABEL = "パンくずリスト";
export const GO_BACK = "戻る";
export const PAGINATION_PAGE_SEPARATOR = "/";
export const PAGINATION_PREV_ARIA_LABEL = "前へ";
export const PAGINATION_NEXT_ARIA_LABEL = "次へ";
export const HOME_TITLE = "ホーム";
export const POSTS_TITLE = "投稿";
export const TAGS_TITLE = "タグ";
export const PRIVACY_POLICY_TITLE = "プライバシーポリシー";
export const CONTACT_TITLE = "お問い合わせ";
export const COPYRIGHT = "Copyright 2024 Daiji";
export const PUBLISHED_DATE_LABEL = "公開: ";
export const UPDATED_DATE_LABEL = "更新: ";
export const FOOTNOTE_LABEL = "脚注";
export const PAGE_SIZE = 20;
export const PICKUP_TITLE = "ピックアップ";
export const PICKUP_POSTS = ["markdown-style-guide", "markdown-style-guide"];
export const HTTP_404_NOT_FOUND_TITLE = "404 Not Found";
export const HTTP_404_NOT_FOUND_TO_TOP = "トップページへ";

export const CONTACT_URL = "https://example.com"
