export const redirects = [
  { from: "about", to: "" },
  { from: "privacy", to: "privacy-policy/" },
  { from: "categories", to: "tags/" },
  { from: "categories/tex-latex", to: "tags/tex/" },
  { from: "categories/日記-備忘録", to: "tags/diary/" },
  { from: "categories/hugo", to: "tags/hugo/" },
  { from: "categories/c", to: "tags/c/" },
  { from: "categories/android", to: "tags/android/" },
  { from: "categories/cdn", to: "tags/cdn/" },
  { from: "categories/python", to: "tags/python/" },
  { from: "categories/プログラミング", to: "tags/programming/" },
  { from: "categories/画像処理", to: "tags/image-processing/" },
  { from: "categories/論文", to: "tags/paper/" },
  { from: "tags/まとめ", to: "tags/memorandum/" },
  { from: "tags/就職活動", to: "tags/job-hunting/" },
  { from: "tags/アルバイト", to: "tags/part-time-job/" },
  { from: "tags/コメント欄", to: "tags/comments-section/" },
  { from: "tags/ネタ", to: "tags/joke/" },
  { from: "tags/翻訳", to: "tags/translation/" },
  { from: "tags/高専", to: "tags/kosen/" },
  { from: "posts/c/popcnt", to: "posts/popcnt/" },
  { from: "posts/tex-latex/tex-word", to: "posts/tex-word/" },
  { from: "posts/c/eval-c", to: "posts/eval-c/" },
  { from: "posts/tex-latex/lualatex-susume", to: "posts/lualatex-susume/" },
  { from: "posts/tex-latex/latex-susume", to: "posts/latex-susume/" },
  { from: "posts/tex-latex/tex-tikz-heatran", to: "posts/tex-tikz-heatran/" },
  { from: "posts/diary/job-hunting", to: "posts/job-hunting/" },
  { from: "posts/diary/atkart-note", to: "posts/atkart-note/" },
  { from: "posts/diary/write-paper", to: "posts/write-paper/" },
  { from: "posts/diary/utterances", to: "posts/utterances/" },
  {
    from: "posts/paper/depth-prediction-without-the-sensors-leveraging-structure-for-unsupervised-learning-from-monocular-videos",
    to: "posts/depth-prediction-without-the-sensors-leveraging-structure-for-unsupervised-learning-from-monocular-videos/",
  },
  { from: "posts/blog/tex2svg", to: "posts/tex2svg/" },
  { from: "posts/hugo/tex2svg", to: "posts/tex2svg/" },
  { from: "posts/blog/yakukumifonts", to: "posts/yakukumi-fonts/" },
  { from: "posts/cdn/yakukumifonts", to: "posts/yakukumi-fonts/" },
  { from: "posts/image-processing/cupy-trans", to: "posts/cupy-trans/" },
  { from: "posts/tex-latex/auto-maze", to: "posts/auto-maze/" },
  { from: "posts/hugo/generate-ogp", to: "posts/generate-ogp/" },
  { from: "posts/diary/fuller-part-1", to: "posts/fuller-part-1/" },
  { from: "posts/diary/kosen-graduation", to: "posts/kosen-graduation/" },
  { from: "posts/diary/onclick-onclicked", to: "posts/onclick-onclicked/" },
];
